name: build
run-name: Build steps for ${{ github.sha }} on ${{ github.ref_name }}

on:
  workflow_call:
    outputs:
      rock:
        description: "rock image"
        value: ${{ jobs.build.outputs.rock }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      rock: ${{ steps.set.outputs.rock }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: canonical/craft-actions/rockcraft-pack@main
        id: rockcraft
      - name: Set rock output
        id: set
        run: echo "rock=${{ steps.rockcraft.outputs.rock }}" >> "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3
        with:
          path: ${{ steps.rockcraft.outputs.rock }}
          name: ${{ steps.rockcraft.outputs.rock }}

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Create SBOM
        run: syft $(realpath ${{ steps.rockcraft.outputs.rock }}) -o spdx-json=identity_platform_login_ui.sbom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3
        with:
          name: identity-platform-login-ui-sbom
          path: "identity_platform_login_ui.sbom.json"
