name: End-to-end tests
run-name: End-to-end test for ${{ github.sha }} on ${{ github.ref_name }}

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: '1.24'
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22

      - name: Install oathtool
        run: |
          sudo apt update
          sudo apt install oathtool

      - name: Boot the cluster with dependant backend systems
        run: |
          ./ui/tests/scripts/01-start-cluster.sh &
          sleep 30 # wait for cluster to boot up

      - name: Start the login ui
        run: |
          ./ui/tests/scripts/02-start-ui.sh &
          curl --head --fail --retry-delay 2 --retry 100 --retry-connrefused --insecure http://localhost:4455/ui/reset_email

      - name: Register a client and boot its container
        run: |
          ./ui/tests/scripts/03-start-oidc-app.sh

      - name: Install Playwright Browser
        run: cd ui && npx playwright install --with-deps chromium

      - name: Run the tests
        run: make test-e2e

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: playwright-results
          path: ui/playwright-report
