name: End-to-end tests
run-name: End-to-end test for ${{ github.sha }} on ${{ github.ref_name }}

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
        with:
          go-version: '1.21'
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 18

      - name: Install oathtool
        run: |
          sudo apt update
          sudo apt install oathtool

      - name: Boot the cluster with dependant backend systems
        run: |
          ./ui/tests/scripts/01-start-cluster.sh &
          sleep 30 # wait for cluster to boot up

      - name: Start the login ui
        run: |
          ./ui/tests/scripts/02-start-ui.sh &
          curl --head --fail --retry-delay 2 --retry 100 --retry-connrefused --insecure http://localhost:4455/ui/reset_email

      - name: Register a client and boot its container
        run: |
          ./ui/tests/scripts/03-start-oidc-app.sh

      - name: Install Playwright Browser
        run: cd ui && npx playwright install --with-deps chromium

      - name: Run the tests
        run: make test-e2e

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
        with:
          name: playwright-results
          path: ui/playwright-report
