name: OCI Image updated

on:
    workflow_dispatch:
        inputs:
            oci-image: 
                description: 'OCI image to use'
                required: true
                type: string

permissions:
    contents: write
    pull-requests: write

jobs:
    update:
        uses: canonical/identity-team/.github/workflows/oci-update-pr.yaml@0a32ad19139490d02dd5283ab91a63295c7a803f
        with: 
            oci-image: ${{ inputs.oci-image }}
            repository: canonical/identity-platform-login-ui-operator
        secrets:
            PAT_TOKEN: ${{ secrets.PAT_TOKEN }}