name: OCI Image updated

on:
    workflow_dispatch:
        inputs:
            oci-image: 
                description: 'OCI image to use'
                required: true
                type: string

permissions:
    contents: write
    pull-requests: write

jobs:
    update:
        uses: canonical/identity-team/.github/workflows/oci-update-pr.yaml@947f2919a0ffe484c198347f23c321a6162680ac
        with: 
            oci-image: ${{ inputs.oci-image }}
            repository: canonical/identity-platform-login-ui-operator
        secrets:
            PAT_TOKEN: ${{ secrets.PAT_TOKEN }}