name: On Main Push

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  unit-test:
    uses: ./.github/workflows/unittest.yaml@main
  build:
    needs: unit-test
    uses: ./.github/workflow/build.yaml@main
  publish:
    needs: build
    uses: ./.github/workflow/publish.yaml@main
  scan:
    needs: publish
    uses: ./.github/workflows/scan.yaml@main