name: On Pull Request

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    uses: ./.github/workflows/unittest.yaml@main
  build:
    needs: unit-test
    uses: ./.github/workflow/build.yaml@main