name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "release-**"

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@db8f2c60ee802b3748b512940dde88eabd7b7e01 # v3
        with:
          release-type: simple
          package-name: ""
          default-branch: main
          pull-request-title-pattern: "ci: release ${version}"
          token: ${{ secrets.PAT_TOKEN }}
          extra-files: |
            rockcraft.yaml
            internal/version/const.go
        id: release
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Workaround for https://github.com/googleapis/release-please/issues/922
        if: ${{ steps.release.outputs.pr != '' }}
        run: |
          echo "Closing and reopening PR to trigger checks"
          gh pr close ${{ fromJSON(steps.release.outputs.pr).number }} || true
          gh pr reopen ${{ fromJSON(steps.release.outputs.pr).number }} || true
          gh pr merge --auto --merge ${{ fromJSON(steps.release.outputs.pr).number }} || true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
