name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "release-**"

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4
        with:
          release-type: simple
          package-name: ""
          default-branch: main
          pull-request-title-pattern: "ci: release ${version}"
          token: ${{ secrets.PAT_TOKEN }}
          extra-files: |
            rockcraft.yaml
            internal/version/const.go
        id: release
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: Workaround for https://github.com/googleapis/release-please/issues/922
        if: ${{ steps.release.outputs.pr != '' }}
        run: |
          echo "Closing and reopening PR to trigger checks"
          gh pr close ${{ fromJSON(steps.release.outputs.pr).number }} || true
          gh pr reopen ${{ fromJSON(steps.release.outputs.pr).number }} || true
          gh pr merge --auto --merge ${{ fromJSON(steps.release.outputs.pr).number }} || true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
