name: container scan
run-name: Scanning container ${{ inputs.image }} to ghcr.io/canonical/identity-platform-login-ui

on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
        description: "image to scan"
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.image }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload scan results to GitHub
        uses: github/codeql-action/upload-sarif@dd196fa9ce80b6bacc74ca1c32bd5b0ba22efca7 # v3
        with:
          sarif_file: 'trivy-results.sarif'
