name: Scan

on:
  workflow_call:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Scan image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: "ghcr.io/canonical/identity-platform-login-ui:latest"
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload scan results to GitHub
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'