name: Upload Go Unit tests

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clean Install of Node version 18
        run: |
          apt update && apt install -y wget
          wget https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh
          bash install.sh
          source /home/runner/.bashrc
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install v18
          nvm use 18
          sudo apt install -y gcc g++ make
      - name: Build UI
        run: |
          pwd
          cd ./ui
          pwd
          npm ci
          npm run build
          pwd
          cd ..
          pwd
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Install dependencies
        run: go get .
      - name: Test with Go
        run: go test -json > TestResults.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results
          path: TestResults.json