name: unit test
run-name: Unit test steps for ${{ github.sha }} on ${{ github.ref_name }}

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build js UI
        run: make npm-build

      - name: Build Go code
        run: make test

      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.out

      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results
          path: test.json
