name: unit test
run-name: Unit test steps for ${{ github.sha }} on ${{ github.ref_name }}

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
        with:
          go-version: '1.21'
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 18

      - name: Build js UI
        run: make npm-build

      - name: Build Go code
        run: make test

      - uses: codecov/codecov-action@0da7aa657d958d32c117fc47e1f977e7524753c7 # v5
        with:
          files: ./coverage.out

      - name: Upload Go test results
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
        with:
          name: Go-results
          path: test.json
